name: Build and run tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake
    - name: Check out
      uses: actions/checkout@v4
    - name: Configure
      run: ./autogen.des
    - name: Build
      run: make
    - name: Run tests
      run: make check
    - name: Run distribution tests
      run: make distcheck
    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-logs
        path: ./**/*.log
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Prepare
      run: |
        brew update
        brew install autoconf automake
    - name: Check out
      uses: actions/checkout@v4
    - name: Configure
      run: ./autogen.des
    - name: Build
      run: make
    - name: Run tests
      run: make check
    - name: Run distribution tests
      run: make distcheck
    - name: Upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: macos-logs
        path: ./**/*.log
